### ISSUE TITLE
Undefined offset in OpenyActivityFinderSolrBackend

### ISSUE THREAD

**Issue by froboy** [ymcatwincities/openy_activity_finder#151]
https://github.com/ymcatwincities/openy_activity_finder/blob/f2e5a79567a9c550d6d9d3fb6d7d083eb6077152/src/OpenyActivityFinderSolrBackend.php#L865

To reproduce:

- enable `openy_prgf_af4_demo`
- Open `/activity-finder-v4`
- Observe notices:

> Notice: Undefined offset: 2 in Drupal\openy_activity_finder\OpenyActivityFinderSolrBackend->convertData() (line 865 of modules/contrib/openy_activity_finder/src/OpenyActivityFinderSolrBackend.php).

**Comment by shelleygoetz** [comment]
Jira ticket here: https://openy.atlassian.net/browse/MAINTAIN-264
