### ISSUE TITLE
Solr >=7 errors on field_session_min_age/max_age

### ISSUE THREAD

**Issue by froboy** [ymcatwincities/openy_activity_finder#153]
As per [this issue on drupal.org](https://www.drupal.org/project/search_api_solr/issues/3009243),  `field_session_min_age` and `field_session_max_age` will throw errors with Solr >=7 and Search_api_solr  4.2.7. This isn't happening on [the sandbox](https://sandbox-carnation-cus-d9.openy.org/activity-finder-v4?step=results) because it's still using Solr 4.

**Observed behavior:**

- spin up an environment with solr 7 or 8
- `drush en openy_prgf_af4_demo`
- see this error on `/activity-finder-v4`

> Drupal\search_api_solr\SearchApiSolrException: Facets having a mincount of "0" is not yet supported by Solr for point based field types. Consider converting the following field to a string or index it twice as string: field_session_min_age. in Drupal\search_api_solr\Plugin\search_api\backend\SearchApiSolrBackend->setFacets() (line 3552 of modules/contrib/search_api_solr/src/Plugin/search_api/backend/SearchApiSolrBackend.php).

**Expected behavior:**
No error and age facets behave as expected.

**Comment by shelleygoetz** [comment]
@froboy Jira ticket created: https://openy.atlassian.net/browse/MAINTAIN-266
