### ISSUE TITLE
[AF4] Notice: Undefined index: background_image

### ISSUE THREAD

**Issue by aleevas** [ymcatwincities/openy_activity_finder#58]
We have this notice in dblog

`Notice: Undefined index: background_image in Drupal\openy_activity_finder\Plugin\Block\ActivityFinder4Block->blockForm() (line 266 of modules/contrib/openy_activity_finder/src/Plugin/Block/ActivityFinder4Block.php).`

Needs to be fixed.

**Comment by duozersk** [comment]
Should be fixed in #59
